### PR TITLE
Add support for 'com.android.library' project

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/41

### CODE REVIEW

**Comment by kattrali** [comment]
Thank you for the report and the contribution, @CAMOBAP795. I'm a little unclear on the usage for this -- how do you use proguard upload tasks from a library instead of an app?

**Comment by CAMOBAP795** [comment]
> how do you use proguard upload tasks from a library instead of an app?
I'm working on SDK for Android which may be used in many different applications

Currently we already have account in https://app.bugsnag.com and it works good except stack trace  'symbolication', it's expectable because we provide pro-guarded version of library for our clients

**Comment by kattrali** [comment]
Gotcha! That makes sense.

**Comment by CAMOBAP795** [comment]
@kattrali 

I just looked in `com.bugsnag.android.Bugsnag` and it looks like it may not work for some cases. Example:
 - in my XXX library I use `com.bugsnag.android.Bugsnag.init(context, "xxxxxxxxx")
 - my client integrate my XXX and it integrate bugsnag also for his own crash reporting
 - client's code calls `com.bugsnag.android.Bugsnag.init(context, "yyyyyyyy") 
Expected result:
 - both my reporting (as XXX library developer) and client's reporting should works
Observed result:
 - depends on who called `com.bugsnag.android.Bugsnag.init` last, it will be 'a winner in this battle'

I know that implementation of such feature isn't easy and will take valuable resources as on SDK side and on Service side also

I just wanna to know do you have any plans to implement this?

-----

Regarding my PR what is the next steps, it will be reviewed someone? how soon I may get some feedback?

**Comment by kattrali** [comment]
I think it wouldn't be too difficult actually, but it would require allowing the exception handler to be chained instead of replaced in the case that its recognized to be a bugsnag handler. [Here is the relevant code](https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/ExceptionHandler.java#L18-L19). For your case, instead of calling `Bugsnag.init`, it may make more sense to instantiate a `Client` object directly, so a user's initialization won't override your own (given the changes described earlier are made to the exception handler behavior).

> I just wanna to know do you have any plans to implement this?
> Regarding my PR what is the next steps, it will be reviewed someone? how soon I may get some feedback?

I think its feasible and useful for similar cases where Bugsnag is being used in an SDK, just not a high priority at the moment. It'll probably be days before a review.

**Comment by CAMOBAP795** [comment]
Hi @kattrali, any update about original topic?

**Comment by fractalwrench** [comment]
[Add support for 'com.android.library' project](https://trello.com/c/sFJVL5KG/9-add-support-for-comandroidlibrary-project)

**Comment by fractalwrench** [comment]
Hi @CAMOBAP795 thanks for the PR. This looks good but I think we'll need to find a replacement for `variantOutput.packageLibrary` as it's deprecated. I'll see if I can find a workaround for this.

**Comment by CAMOBAP795** [comment]
@fractalwrench thanks, do you need some help/info from my side?

**Comment by fractalwrench** [comment]
@CAMOBAP795 if you happen to know of an alternative to `variantOutput.packageLibrary` that would be helpful - otherwise I can investigate which task will work for both applications and libraries.

**Comment by CAMOBAP795** [comment]
@fractalwrench sorry cannot help with this

**Comment by fractalwrench** [comment]
@CAMOBAP795 no problem. I've got a feeling that it should be possible to use `build.finalizedBy` for this, so will try that out.

**Comment by fractalwrench** [comment]
Closing in favour of #61, as there have been substantial changes to the plugin since this PR was opened.

**Pull request closed without merging**
