### PR TITLE
Add basic unity E2E test fixtures

### PR DESCRIPTION
**Pull request by fractalwrench**
## Goal

Adds basic E2E test fixtures for Unity 2018.4 and Unity 2019.4 [exported Gradle projects](https://docs.unity3d.com/Manual/android-gradle-overview.html). These have been generated from the bugsnag-unity example project, obfuscation has been enabled, and the bugsnag gradle plugin has been applied to the project.

Currently this just ensures that the Unity projects upload JVM mapping files and release information. Separate changesets will be made to verify that SO files for NDK + Unity can be uploaded.

### CODE REVIEW

**Review by twometresteve — COMMENTED** [review]
Looks like a sensible direction from a test perspective - without knowing or looking at the details of BAGP and Unity.

**Review by imjoehaines — APPROVED** [review]
Can these be added to Travis yet (even if they don't test much ATM)?

**Comment by fractalwrench** [comment]
`features/unity.feature` should run on Travis automatically. #312 will add some additional depth to the scenarios to verify the SO files are generated and uploaded for Unity.

**Comment by imjoehaines** [comment]
> `features/unity.feature` should run on Travis automatically. #312 will add some additional depth to the scenarios to verify the SO files are generated and uploaded for Unity.

👍 I see them on Travis now — not sure what happened when I looked the first time!

**Pull request merged**
