### PR TITLE
Support uploading via proxy connections if proxy system properties are set

### LINKED ISSUE #199: Mappings fail to upload when behind a proxy
### Expected behavior
Bugsnag uploads succeed

### Observed behavior
Uploads fail with the following message:
"Unable to tunnel through proxy. Proxy returns “HTTP/1.1 407 Proxy Authentication Required”"

### Steps to reproduce
Attempt to access upload.bugsnag.com via a proxy connection

### Version
4.7.4

### Additional information

After upgrading from 4.0.0 to 4.7.4, we started to see CI build failures when running the uploadBugsnag${VARIANT}Mapping task.

```
18:29:58  Attempting upload of mapping file to Bugsnag
18:29:58  Bugsnag upload failed: java.net.ConnectException: Connection refused (Connection refused)
18:29:58  
...
18:29:59  
18:29:59  > Task :app:bugsnagReleaseInternal-releaseTask
18:29:59  https://build.bugsnag.com
18:29:59  Failed to POST request
18:29:59  java.io.IOException: Unable to tunnel through proxy. Proxy returns “HTTP/1.1 407 Proxy Authentication Required”
18:29:59  	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
```

While reviewing and comparing current and past build logs, we discovered this error message has been logged for awhile, but only surfaced due to [this change in 4.1.0](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v4.1.0):

```
Note: this version of the plugin will fail the build if a mapping file is not uploaded successfully.
Previously if this occurred the failure would have been logged as an error and the build would have continued.
```

The root cause: some workers in our CI infrastructure can only make outbound internet connections via an internal proxy, but it appears the upload mapping task currently doesn't support proxy connections or proxy authentication.

### PR DESCRIPTION
**Pull request by jrodbx**
Closes #199

## Goal
Details in #199 

## Design
Allows opt-in support for proxy connections

## Changeset
The uploading client setup in `BugsnagMultiPartUploadTask`

## Tests
No tests currently exist for this task.  Instead, I first tested locally by installing to mavenLocal and debugged the plugin's execution using `-Dorg.gradle.debug=true` and remote attaching a debugger.  Then, I pushed to our internal artifact repository and tested a CI build.  A different error message (403 forbidden) resulted since we currently don't have a proxy whitelist entry for  `upload.bugsnag.com`.  However, the proxy connection and authentication issues have been resolved.

### CODE REVIEW

**Comment by jrodbx** [comment]
@fractalwrench i see you updated a few PRs in this project, wondering if you had any thoughts on this one?

**Comment by fractalwrench** [comment]
Hi @jrodbx - thanks for making this contribution. Supporting proxy connections seems like a reasonable feature and is something we'd like to add to the plugin. Our next focus will be ensuring compatibility with AGP 4.1 but this feature is something we'd like to implement after that. Thanks again

**Comment by jrodbx** [comment]
hi @fractalwrench what's the state of your AGP 4.1 compatibility effort?  would this PR have a shot of making an upcoming release soon?  without it, we're still unfortunately unable to upload our mapping files via the Bugsnag Gradle Plugin in our Jenkins builds which push our alpha builds to an internal Play Store due to a proxy configuration.

**Comment by johnkiely1** [comment]
Hi @jrodbx 

We are currently working on AGP 4.1 compatibility as part of a larger change which includes some other improvements to the plugin itself. At this stage we don't have a confirmed timeline yet for when this will be ready for release.

**Comment by ZacSweers** [comment]
I took a stab at reimplementing this in the new okhttp stack in #270

**Comment by fractalwrench** [comment]
Thanks for the contribution @jrodbx - we're planning on accepting Zac's PR #270. We're currently planning some automated tests for this functionality so will review the PR when that work is finished.

**Pull request closed without merging**
